# Generated by Django 4.2.3 on 2023-09-14 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barber_shop', '0028_company_owner_is_employee'),
        ('users', '0008_alter_userprofile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='type',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('barbeiro', 'Barbeiro'), ('dono', 'Dono')], default='cliente', max_length=50, verbose_name='Tipo do usuário'),
        ),
        migrations.CreateModel(
            name='Barbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_barber', models.EmailField(max_length=254, unique=True, verbose_name='Email do barbeiro')),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Barbeiro')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barber_shop.company', verbose_name='Barbearia')),
            ],
            options={
                'verbose_name': 'Barbeiro',
                'verbose_name_plural': 'Barbeiros',
            },
        ),
    ]
