# Generated by Django 4.2.3 on 2023-09-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_barbers_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbers',
            name='password',
            field=models.CharField(default='', max_length=12, verbose_name='Senha'),
        ),
    ]
