# Generated by Django 4.2.3 on 2023-09-30 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_barbers_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='owner',
            new_name='is_owner',
        ),
    ]
