# Generated by Django 4.2.3 on 2023-10-01 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0013_rename_owner_userprofile_is_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cut_price', models.FloatField(verbose_name='Preço do corte')),
                ('cut_description', models.CharField(verbose_name='Tipo do corte')),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.barbers', verbose_name='Barbeiro')),
            ],
            options={
                'verbose_name': 'Preço do corte',
                'verbose_name_plural': 'Preços dos cortes',
            },
        ),
    ]
