# Generated by Django 4.2.3 on 2023-10-02 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prices',
            name='cut_photo',
            field=models.ImageField(default='', upload_to='', verbose_name='Foto do corte'),
        ),
    ]
