# Generated by Django 4.2.3 on 2023-10-06 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_rename_owner_userprofile_is_owner'),
        ('prices', '0002_prices_cut_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices',
            name='barber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.barbers', verbose_name='Barbeiro'),
        ),
    ]
