# Generated by Django 4.2.3 on 2023-10-06 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0003_alter_prices_barber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prices',
            name='barber',
        ),
    ]
