# Generated by Django 4.2.3 on 2023-08-17 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0003_alter_abousus_developed_by_alter_abousus_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsOfUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Titulo')),
                ('terms_of_use', models.FileField(blank=True, null=True, upload_to='terms_of_use/', verbose_name='Termos de Uso')),
            ],
            options={
                'verbose_name': 'Termo de Uso',
                'verbose_name_plural': 'Termos de Uso',
            },
        ),
    ]
