# Generated by Django 4.2.3 on 2023-07-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber_shop', '0013_days_hours_business'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='days',
            options={'verbose_name': 'Dia', 'verbose_name_plural': 'Dias de Funcionamento'},
        ),
        migrations.RemoveField(
            model_name='days',
            name='hours_business',
        ),
        migrations.AddField(
            model_name='days',
            name='end',
            field=models.DateTimeField(auto_created=True, null=True, verbose_name='Horário de encerramento'),
        ),
        migrations.AddField(
            model_name='days',
            name='pause_time',
            field=models.DateTimeField(blank=True, help_text='(opcional)', null=True, verbose_name='Horário de pausa'),
        ),
        migrations.AddField(
            model_name='days',
            name='start',
            field=models.TimeField(auto_created=True, null=True, verbose_name='Horário de inicio'),
        ),
    ]
