# Generated by Django 4.2.3 on 2023-07-30 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber_shop', '0014_alter_days_options_remove_days_hours_business_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='days',
            name='end',
        ),
        migrations.AddField(
            model_name='days',
            name='end_time',
            field=models.TimeField(auto_created=True, null=True, verbose_name='Horário de encerramento'),
        ),
        migrations.AlterField(
            model_name='days',
            name='pause_time',
            field=models.TimeField(blank=True, help_text='(opcional)', null=True, verbose_name='Horário de pausa'),
        ),
    ]
