# Generated by Django 4.2.3 on 2023-08-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber_shop', '0016_days_end_pause_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='days',
            name='end_pause_time',
            field=models.TimeField(blank=True, help_text='(opcional)', null=True, verbose_name='Fim da pausa'),
        ),
    ]
