# Generated by Django 4.2.3 on 2023-08-01 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barber_shop', '0017_alter_days_end_pause_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedules',
            name='barbershop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='barber_shop.company', verbose_name='Barbearia'),
            preserve_default=False,
        ),
    ]
