# Generated by Django 4.2.3 on 2023-08-02 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barber_shop', '0018_schedules_barbershop'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulesDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(verbose_name='Data')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_day', to='barber_shop.days', verbose_name='Dia')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule', to='barber_shop.schedules', verbose_name='Agendado por')),
            ],
            options={
                'verbose_name': 'Dia agendado',
                'verbose_name_plural': 'Dias agendados',
            },
        ),
    ]
