# Generated by Django 4.2.3 on 2023-08-02 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barber_shop', '0019_schedulesdays'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedules',
            name='day',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='schedules_days', to='barber_shop.days', verbose_name='Dia'),
            preserve_default=False,
        ),
    ]
