# Generated by Django 4.2.3 on 2023-08-02 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barber_shop', '0020_schedules_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='days',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_dat', to='barber_shop.company', verbose_name='Barbearia'),
        ),
    ]
