# Generated by Django 4.2.3 on 2023-08-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber_shop', '0021_alter_days_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedules',
            name='user_canceled',
            field=models.BooleanField(default=False, verbose_name='Cancelado pelo usuário?'),
        ),
    ]
