# Generated by Django 4.2.3 on 2023-08-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber_shop', '0022_schedules_user_canceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='days',
            name='working_day',
            field=models.BooleanField(default=True, verbose_name='Dia de funcionamento normal'),
        ),
    ]
