# Generated by Django 4.2.3 on 2023-08-25 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber_shop', '0023_days_working_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='days',
            name='working_day',
            field=models.BooleanField(default=True, verbose_name='Dia de funcionamento'),
        ),
    ]
