# Generated by Django 4.2.3 on 2023-08-31 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber_shop', '0025_company_number_alter_company_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='number',
            field=models.CharField(default='', verbose_name='Número do endereço'),
        ),
    ]
