# Generated by Django 4.2.3 on 2023-08-31 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barber_shop', '0026_alter_company_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulesdays',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_day', to='barber_shop.days', verbose_name='Dia'),
        ),
        migrations.AlterField(
            model_name='schedulesdays',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='barber_shop.schedules', verbose_name='Agendado por'),
        ),
    ]
