# Generated by Django 4.2.3 on 2023-09-14 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber_shop', '0027_alter_schedulesdays_day_alter_schedulesdays_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='owner_is_employee',
            field=models.BooleanField(default=True, verbose_name='Dono e funcionário'),
        ),
    ]
