# Generated by Django 4.2.3 on 2023-10-06 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0002_prices_cut_photo'),
        ('barber_shop', '0029_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedules',
            name='chosen_cut',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='prices.prices', verbose_name='Corte escolhido'),
            preserve_default=False,
        ),
    ]
